# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4wBxlg-rHLlnG67xWqzEYd6fASGmY_Q

# «Умные» бионические таблетки: моделирование контролируемого высвобождения лекарственных средств и прогнозирование рисков на основе ИИ в персонализированной медицине.

## Введение

Современная медицина активно переходит к персонализированным подходам лечения,
где ключевую роль играют системы контролируемой доставки лекарств.

Бионические таблетки, оснащённые микрочипами, позволяют:
- управлять скоростью высвобождения препарата
- отслеживать соблюдение терапии
- адаптировать лечение под индивидуальные параметры пациента

Подобные технологии разрабатывались, например, компанией Proteus Digital Health.

Цель данного исследования — смоделировать систему контролируемого высвобождения
и оценить возможность прогнозирования риска нарушения терапии с помощью
методов машинного обучения.

## Гипотеза


Контролируемое высвобождение лекарственного вещества,
в сочетании с мониторингом физиологических параметров пациента,
позволяет прогнозировать риск нарушения терапии.

Предполагается, что:
- частота пропуска доз является ключевым фактором риска
- физиологические параметры усиливают вероятность нарушения терапии

*установка библиотек*
"""

!pip install ipywidgets seaborn scikit-learn

"""*импорты*"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ipywidgets import interact, FloatSlider, IntSlider
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

np.random.seed(42)

"""## Математическая модель высвобождения лекарств

Высвобождение лекарственного вещества описывается экспоненциальной моделью первого порядка:

$$
C(t) = D \cdot (1 - e^{-kt})
$$

где:
- C(t) — количество высвобожденного вещества  
- D — доза  
- k — коэффициент скорости  
- t — время  

Модель широко используется в фармакокинетике.

функция + *интерактив*
"""

from ipywidgets import interact, FloatSlider
import numpy as np
import matplotlib.pyplot as plt

def drug_release(time, dose, speed):
    return dose * (1 - np.exp(-speed * time))


@interact(
    dose=FloatSlider(min=50, max=500, step=10, value=200),
    speed=FloatSlider(min=0.05, max=1.0, step=0.05, value=0.3)
)
def interactive_plot(dose, speed):
    time = np.linspace(0, 10, 100)
    released = drug_release(time, dose, speed)

    plt.figure(figsize=(8,4))
    plt.plot(time, released)
    plt.fill_between(time, released, alpha=0.3)
    plt.xlabel("Time (hours)")
    plt.ylabel("Released drug (mg)")
    plt.title("Controlled Drug Release")
    plt.grid(True)
    plt.show()

"""## Визуализация динамики

Анимации демонстрирует процесс высвобождения лекарственного вещества
и влияние параметров на скорость доставки препарата.
"""

from matplotlib.animation import FuncAnimation
from IPython.display import HTML

fig, ax = plt.subplots(figsize=(7,4))

time = np.linspace(0, 10, 100)
dose = 250
speed = 0.4

line, = ax.plot([], [], lw=3)
ax.set_xlim(0, 10)
ax.set_ylim(0, dose)
ax.set_xlabel("Time (hours)")
ax.set_ylabel("Released drug (mg)")
ax.set_title("Dynamic Drug Release Process")

def animate(i):
    x = time[:i]
    y = drug_release(x, dose, speed)
    line.set_data(x, y)
    return line,

anim = FuncAnimation(fig, animate, frames=len(time), interval=80)

HTML(anim.to_jshtml())

"""*влияние скорости*"""

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(7,4))

time = np.linspace(0, 10, 100)
dose = 250

line, = ax.plot([], [], lw=3)

ax.set_xlim(0, 10)
ax.set_ylim(0, dose)
ax.set_xlabel("Time (hours)")
ax.set_ylabel("Released drug (mg)")
ax.set_title("Effect of Release Rate on Drug Delivery")

def animate(i):
    speed = 0.1 + i * 0.02
    y = drug_release(time, dose, speed)
    line.set_data(time, y)
    return line,

anim = FuncAnimation(fig, animate, frames=30, interval=100)

HTML(anim.to_jshtml())

"""## Data Generation

Так как реальные клинические данные недоступны,
используются синтетические данные пациентов.
"""

n = 500

data = pd.DataFrame({
    "age": np.random.randint(18, 80, n),
    "dose_mg": np.random.randint(100, 400, n),
    "pH": np.random.uniform(1.5, 7.5, n),
    "missed_doses": np.random.randint(0, 6, n),
    "heart_rate": np.random.randint(60, 110, n)
})

data["high_risk"] = (
    (data["missed_doses"] > 2) |
    ((data["heart_rate"] > 95) & (data["age"] > 50))
).astype(int)

data.head()

"""## Machine Learning Model"""

X = data.drop("high_risk", axis=1)
y = data["high_risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest accuracy:", accuracy_score(y_test, rf_pred))

"""сравнение *моделей*"""

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

print("Logistic Regression accuracy:", accuracy_score(y_test, log_pred))

"""*визуализации*"""

plt.figure(figsize=(8,6))
sns.heatmap(data.corr(), annot=True)
plt.title("Correlation Matrix")
plt.show()


importance = rf_model.feature_importances_

plt.figure(figsize=(8,5))
plt.bar(X.columns, importance)
plt.title("Feature Importance")
plt.xticks(rotation=45)
plt.show()


cm = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()

"""## Patient Simulation and AI Prediction

Для демонстрации практического применения модели
была реализована симуляция пациента во времени.

Параметры пациента изменяются динамически,
а модель оценивает риск нарушения терапии на каждом шаге.
"""

import random
import time
from IPython.display import clear_output

risk_history = []

for step in range(20):

    # симуляция пациента
    age = random.randint(20, 70)
    dose = random.randint(150, 350)
    pH = random.uniform(1.5, 7.5)
    missed_doses = random.randint(0, 5)
    heart_rate = random.randint(60, 110)

    patient = [[age, dose, pH, missed_doses, heart_rate]]

    # прогноз модели
    risk = rf_model.predict(patient)[0]

    risk_history.append(risk)

    clear_output(wait=True)

    print("PATIENT STATE")
    print("----------------------")
    print("Age:", age)
    print("Dose:", dose)
    print("pH:", round(pH,2))
    print("Missed doses:", missed_doses)
    print("Heart rate:", heart_rate)

    if risk == 1:
        print("⚠ High risk of therapy non-adherence")
    else:
        print("✔ Low risk")

    # график риска
    plt.figure(figsize=(6,3))
    plt.plot(risk_history, marker='o')
    plt.title("Risk Dynamics")
    plt.xlabel("Time step")
    plt.ylabel("Risk")
    plt.ylim(-0.1,1.1)
    plt.grid(True)
    plt.show()

    time.sleep(1)

"""Данная симуляция демонстрирует,
как интеллектуальная система может отслеживать состояние пациента
и выявлять периоды повышенного риска.

Это подтверждает гипотезу о том,
что анализ параметров пациента позволяет прогнозировать
нарушение терапии.

## Discussion

Результаты показывают, что:
- пропущенные дозы являются ключевым фактором риска
- физиологические параметры усиливают влияние

Ограничения:
- синтетические данные
- упрощённая модель
- отсутствие клинической валидации

## Conclusion

Модель бионической таблетки демонстрирует потенциал
для применения в персонализированной медицине.

Комбинация фармакокинетики и машинного обучения
может использоваться для прогнозирования риска
и повышения эффективности лечения.

Дальнейшие исследования требуют реальных данных.
"""